### ISSUE TITLE
SFrame/SPacket

### ISSUE THREAD

**Issue by aboba** [mengelbart/rtp-over-quic-draft#29] opened 2022-08-03 18:56 UTC
The spec does not currently describe how [SFrame](https://datatracker.ietf.org/doc/draft-ietf-sframe-enc/) is supported in RTP over QUIC, or what an RTP translator should do. One way to address this would be to add a section that would deal with the issues that come up when implementing [SFrame](https://datatracker.ietf.org/doc/draft-ietf-sframe-enc/) in RTP over QUIC.

**Comment by mengelbart** [comment] 2022-09-19 10:41
I may be missing some background on SFrame/SPacket, but as far as I understand the document you linked, SFrame tries to be independent of the underlying transport, so I don't understand why the RTP over QUIC document should cover its usage. Could you explain why SFrame should only be used with QUIC streams and SPacket only in QUIC datagrams?

**Comment by aboba** [comment] 2022-09-20 18:48
SFrame encrypts an entire frame, making it opaque.  This creates a problem for the RTP packetizer, which is codec specific; there is no "generic packetization" defined in RTP.   However, if the SFrame doesn't need to be packetized (e.g. it is put into a QUIC stream) this is not an issue. 

SPacket achieves compatibility with RTP packetization by packetizing the frame *before* encryption/integrity protection. So SPacket is compatible with RTP over UDP as well as RTP over QUIC datagrams.

**Comment by mengelbart** [comment] 2022-09-21 11:37
> if the SFrame doesn't need to be packetized (e.g. it is put into a QUIC stream) this is not an issue.

The frame would still be packetized in RTP packets in both QUIC datagrams and streams. The RTP packet size in a QUIC stream may be much larger (containing the entire frame instead of just one fragment), and each stream can only be used for one RTP packet.

If I understand it correctly, RTP over QUIC (Datagrams and Streams) would have the same support (and issues) for SFrame/SPacket as RTP over UDP?

**Comment by aboba** [comment] 2022-11-07 01:33
There are issues with the implementation of RTP translation between RTP over QUIC and RTP/UDP, regardless of whether RTP over QUIC uses QUIC reliable streams or datagrams: 

1. When RTP over QUIC is transported in a QUIC reliable stream, the MTU size is much larger (could be infinite) than the RTP over UDP MTU.  So the RTP/QUIC payload needs to be re-packetized to be sent over RTP/UDP. 

2. When RTP/UDP is translated to RTP over QUIC datagrams, there can also be a re-packetization issue. If the UDP MTU is larger than the QUIC datagram MTU, then re-packetization would be required or else the RTP over QUIC datagrams could be fragmented. 

SFrame complicates these issues further since the RTP payloads are opaque, and are thus not amenable to re-packetization.

**Comment by aboba** [comment] 2022-11-07 01:38
Related: https://github.com/pthatcher/sframe-over-rtp-over-quic-draft/blob/main/draft-pthatcher-sframe-over-rtp-over-quic.txt

**Comment by pthatcher** [comment] 2022-11-07 14:43
I tried to explain the issue in the draft I wrote to solve this. 

The gist is that the problem is when a translator has larger RTP packets on one side smaller RTP packets on the other.   QUIC streams allow for very large RTP packets, and the translator has to deal with that.  The RTP-over-QUIC document says that the solution is to use "codec-specific packetization", but when SFrame encrypts the codec, it effectively becomes the codec, so you need, basically, an SFrame-specific way to repacketize a large RTP packet containing SFrame into smaller RTP packets containing SFrame.   SPacket doesn't help because we're talking about large RTP packets, and SPackets will still have the same problem.  

So what I wrote in the draft Bernard just linked to is a mechanism to repacketize a large RTP packet containing SFrame (or SPacket; that works too) into smaller RTP packets containing SFrame (or SPacket).

It also discusses and supports the other direction: turning many smaller RTP packets back into one large RTP packet (translating the other way).

**Comment by SpencerDawkins** [comment] 2023-03-09 16:42
Hi, @pthatcher, @mengelbart and I think this question is being handled as generic for RTP, not for RTP-over-QUIC, and the relevant Githubs (draft-pthatcher-sframe-over-rtp-over-quic and draft-codec-agnostic-rtp-payload-format) are where this will be worked out. Is that also your understanding?

**Comment by SpencerDawkins** [comment] 2023-10-16 14:37
@mengelbart and @SpencerDawkins have reflected on this issue several times, and we are thinking 

- there's not much we can say in the RoQ draft that is specific to RoQ - whatever one does with RTP in SFrames would be the same with RTP over QUIC in SFrames
- we would love to be able to repacketize SFrames (especially if there is a problem with PMTU size), but that's not RoQ-specific, either
- RoQ does include a length field, so that an endpoint can do something about that, if it needs to. 

We're happy to listen to reason, and closed issues can be reopened in GitHub, but we're closing this one, for now.

**Closed** 2023-10-16 14:37 UTC
Labels: question, wontfix, NotJustRTP, external doc
